#ifndef ENDPROJECT_ERROR_HANDLER_H
#define ENDPROJECT_ERROR_HANDLER_H

typedef enum {
    ERR_LABEL,
    ERR_EXPECTED_ARG,
    ERR_EXPECTED_LABEL,
    ERR_INV_WORD,
    ERR_INV_DATA_PARAM,
    ERR_INV_DATA_SIZE,
    ERR_INV_STRING_PARAM,
    ERR_INV_DIRECTIVE,
    ERR_INV_MAT_PARAM,
    ERR_INV_MAT_INIT,
    ERR_INV_MAT_PARAM_SIZE,
    ERR_INV_EXTRA_COMMA,
    ERR_EXSS_MAT_VAL,
    ERR_STOP,
    ERR_LABEL_REDECLARED,
    NO_ERR_OCCURRED,
    E_UNDECLARED_SYMBOL,
    E_INVALID_ADDMODE,
    E_INVALID_SRCOP_ADDMODE,
    E_INVALID_DESTOP_ADDMODE,
    E_MISS_OP
}ErrorTypes;

void print_error(ErrorTypes err, int lineNum, char *line);
#endif /*ENDPROJECT_ERROR_HANDLER_H*/
